version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - "./cloud_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - "4345:5432"
    networks:
      - custom_network

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: julian-padilla@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: JulianP4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - custom_network

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - custom_network

  web:
    build: .
    command: sh -c "flask run --host=0.0.0.0 --port=8080"
    ports:
      - "8080:8080"
    networks:
      - custom_network
    volumes:
      - celery_volume:/usr/src/app
      - ./videos-subidos:/cloud-docker/videos/subidos
      - ./videos-procesados:/cloud-docker/videos/procesados

  celery:
    build: .
    command: sh -c "celery --app tareas.celery worker --loglevel=info"
    networks:
      - custom_network
    volumes:
      - ./videos-subidos:/cloud-docker/videos/subidos
      - ./videos-procesados:/cloud-docker/videos/procesados

networks:
  custom_network:
    driver: bridge

volumes:
  pgadmin-data:
  cache:
  celery_volume: