services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - "./cloud_data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/db
    ports:
      - "4345:5432"
