on: [push]
permissions: write-all
jobs:
  publish-docker-img-amd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          version: latest
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker buildx build -t santiago9913/flask:latest --platform linux/amd64 linux/arm/v8 linux/arm64 .
          docker push santiago9913/flask:latest
